# Helpers are user-defined functions that can be executed inside templates.
# This section is optional.
[helpers]

[default]
depends = ["bash","git","inputrc"]

[default.files]

[default.variables]

[bash.files]
bash_aliases = "~/.bash_aliases"
bashrc = "~/.bashrc"

[bat.files]
bat = "~/.config/bat/config"

[git.files]
gitconfig = "~/.gitconfig"

[inputrc.files]
inputrc = "~/.inputrc"

[vim.files]
vimrc = "~/.vimrc"
vim_plug = "~/.vim/autoload/plug.vim"

[nvim.files]
vimrc = "~/.config/nvim/init.vim"
vim_plug = "~/.local/share/nvim/site/autoload/plug.vim"

[tmux.files]
tmux_conf = "~/.config/tmux/tmux.conf"

[ripgrep.files]
ripgrep = "~/.config/ripgrep/.ripgreprc"

